# fly.toml app configuration file generated for gen-ai-medical-chatbot on 2025-05-16T18:46:01+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gen-ai-medical-chatbot'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 500

  [[http_service.checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"
    method = "get"
    path = "/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

